# **Adventure Work Analysis**



# **Introduction**

The aim of this project is to show the steps to analyse the activities of the company between the year 2020-2022. This starts from the data definition language stage and Data manipulation stage in SSMS to reporting in SSRS. This analyses is focused on different categores discussed below to ensure increased revenue/profit generation, improved customers satisfaction and reduced return rate. The analysis has been done using the below parameters:

##

-  The Revenue/Profit generation by products category, territory and Year: To help understand where the business is doing well and where improvements are necessary. 
-  The Highest grossing customer: This would help in understanding our customers as it is only when we udnerstand them that we can provide them with unmatched customer satisfaction taht would eventually improve our bottomlines
-  The return rate: High return would mean defective products or lack of customers' fulfillment and eventual loss of revenue. This analysis will give an insight into the products with the highest retune, and this could help in identifying any undetected issue in the product production.

##  **The Dataset**

The dataset contains the sales and return tables between the year 2020-2022. Both tables contains the measurable information ablot the company such as sales, orderd quantity, and quantity returned. It also has the dimension tables calendar, customers, product, product categories, product subcategories and Territory.

## **Data Source**

The data [AdventureWorks](https://www.kaggle.com/datasets/algorismus/adventure-works-in-excel-tables) used for this project was sourced from kaggel.

## **The Business Questions to be Addressed**

<a name="lists" />


1. The yearly revenue and profits for the year under review: This is important to understand the year on year trend and to identify any sign of revenue/profit decline and to take immediate action in case of any sign of deterioration.
2. The monthly revenue to show the trend: This helps to understand the months seaons and the products that sell fasts in each periods.
3. The highest grossing product category by total order, total revenue and total profit: This will be used for the evaluation of each products category and to establish which product line brings in the highest revenue/profit for additioanl investment and if products should be discountinued if any.
4. The highest grossing customers by revenue and profits: This helps in customer segmentation. Knowing the highest grossing customer can help in prioritsing our customers in other to serve them better. This categories of customer, when identified can help to understand areas of improvement so as to retain them and to also device means to market low grossing customers.
5. The highest grossing Territory: This will be important for marketing strategies to identify territories that are performing well and those below expectation.
6. Return rate: This is used to dientify the highest returned product and to identify reason for such return. Could they be due to product defects or issues with the product production process.


## **ERD**

This has been created using the [Kimball Star Schema](https://www.kimballgroup.com/data-warehouse-business-intelligence-resources/kimball-techniques/dimensional-modeling-techniques/) approach

![ERD](./Adventure-Works-ERD.drawio.png)


## **Steps to Mart Creation (DDL)**

After obtaining the data to be used for my analysis, the next step is to create the mart using T-SQL against a MS SQl server 2022.

- **Database**: The database table is firstly created to warehouse all the data to be used for this project. For this project the database table is named Project.

##  Schemas

Schmas are important in SQL to ensure data security, organization and management. It allows for the logical categorization of related databases. e.g facts tables, dims and stg. For this project, the schemas stg, dim and f for facts were created. After the creation of each schemas, refesh the database and the created schemas are located in the security folder in the database.

# Steps are:

-  Use the IF NOT EXISTS statement to query the system if the schemas stg, fact and dim exist. If not exist, then we begin by creating the schemas below.

- **Stg**
- **fact**
- **dim**

```sql

IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'dim' ) 
BEGIN
	EXEC sp_executesql N'CREATE SCHEMA dim AUTHORIZATION dbo;'
END
;

GO

IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'stg' ) 
BEGIN
	EXEC sp_executesql N'CREATE SCHEMA stg AUTHORIZATION dbo;'
END
;

GO

IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'f' ) 
BEGIN
	EXEC sp_executesql N'CREATE SCHEMA f AUTHORIZATION dbo;'
END
;

GO

```
##  **Steps to Dimension Creation**

The next step would be creation of dimension table also know as dim tables. The dim tables are used in data warehouses to complement the fact tables. Dim tables warehouses descriptive attributes about business entities such as calendars, customers, products, Territories etc. seperate from transactional or numerical data. For this project the below dim tables were created:

## Understanding Common Terms

-  DataTypes: This could be DateTIme, Int, varchar or nvarchar. The right choice will depend on the data type being referenced. DateDate is used for date, int for nuemrics, varchar for texts.

-  NULL/NOT NULL: NULL is used where values can be empty in a table while NOT NULL is used for fields taht cannot be left empty.


##  dim. Calendar Creation:


This table is to warehouse the date of the transactions in year, month and quarterly periods. The Order date used as the primary key, which is unique. 

# Code Explanation

-  First query SQl using the IF NOT EXIST statement to ascertain the existence of table name Calendar in the dim schema
-  If not exist, the begin syntax will start the process to create the dim. calendar table
-  The required columns are created such as OrderDate, Year, Quarter, Month and MonthName. The datetime refers tot he OrderDate datatype while int refers to the data type of numerical values. NOT NULL refers to values can not be empty. The nvarchar data type is used for MonthName as it containes texts.
-  After specifying the columns with there data types and NULL/NOT NULL. We move to Alter the table. Table altering is an instruction for the query in the table to be changed.
-  The next would be to Add Contraint, in this case, add the OrderDate as the PrimaryKey constraint.
-  End and GO to mark the end of the batch, and instructing SQL to execute all preceding code as a single operation.

## dim.Customers Creation: 

This table is to warehouse the customer information such as their unique identifier, their name, occupation, income level etc. The customer key is assigned as the primary key.

# Code Explanation

-  First query SQl using the IF NOT EXIST statement to ascertain the existence of table name Customer in the dim schema
-  If not exist, the begin syntax will start the process to create the dim. Customer table
-  The required columns are created such as CustomerKey (this is the unique identifier for each of the customers), BirthDate,Gender,Gender,EmailAddress,TotalChildren, EducationLevel, Occupation, Homeowwner,Parent, Customer Priority and Income level.  Datatype int refers to the data type of numerical values. NOT NULL refers to values can not be empty. The nvarchar data type is used for columns that contain texts.
-  After specifying the columns with there data types and NULL/NOT NULL. We move to Alter the table. Table altering is an instruction for the query in the table to be changed.
-  The next would be to Add Contraint, in this case, add the Customerkey which is each customer's unique identifer as the PrimaryKey constraint.
-  End and GO to mark the end of the batch, and instructing SQL to execute all preceding code as a single operation.


## dim.Products Creation: 

This is to warehouse the products information such as productname, cost, color etc

# Code Explanation

-  First query SQl using the IF NOT EXIST statement to ascertain the existence of table name Products in the dim schema
-  If not exist, the begin syntax will start the process to create the dim. Products table
-  The required columns are description of the products such as ProductKey,ProductSubcategory, ProductName, ProductColor, ProductCost, ProductPrice and DiscountPrice. The productKey is the unique identifier for each of the producst,  Datatype int refers to the data type of numerical values. NOT NULL refers to values can not be empty. The nvarchar data type is used for ProductName as it contains texts.
-  After specifying the columns with there data types and NULL/NOT NULL. We move to Alter the table. Table altering is an instruction for the query in the table to be changed.
-  The next would be to Add Contraint, in this case, add the Productkey which is each customer's unique identifer as the PrimaryKey constraint.
-  End and GO to mark the end of the batch, and instructing SQL to execute all preceding code as a single operation.

## dim.ProductsCategory Creation: 

This is to warehouse the various ProductCategories. This put the producst into bigger buckets for monitoring and managing across categories.

# Code Explanation

-  First query SQl using the IF NOT EXIST statement to ascertain the existence of table name ProductsCategory in the dim schema
-  If not exist, the begin syntax will start the process to create the dim. ProductsCategory table
-  The required columns are description of the productcategories such as Productcategorykey and the ProductCategoryName. The ProductCategory Key is the unique identifier for each of the productcategory,  Datatype int refers to the data type of numerical values. NOT NULL refers to values can not be empty. The nvarchar data type is used for CategoryName as it contains texts.
-  After specifying the columns with there data types and NULL/NOT NULL. We move to Alter the table. Table altering is an instruction for the query in the table to be changed.
-  The next would be to Add Contraint, in this case, add the ProductCategory key which is each category's unique identifer as the PrimaryKey constraint.
-  End and GO to mark the end of the batch, and instructing SQL to execute all preceding code as a single operation.


## dim.ProductSubCategory Creation: 

This is to warehouse the various ProductSubCategories. This breakds down the products into smaller chunks.

# Code Explanation

-  First query SQl using the IF NOT EXIST statement to ascertain the existence of table name ProductSubCategory in the dim schema
-  If not exist, the begin syntax will start the process to create the dim. ProductSubCategory table
-  The required columns are description of the productsubcategories such as ProductSubcategorykey, SubCategoryName, ProductCategoryKey. The ProductSubCategory Key is the unique identifier for each of the Subcategory,  Datatype int refers to the data type of numerical values. NOT NULL refers to values can not be empty. The nvarchar data type is used for SubCategoryName as it contains texts.
-  After specifying the columns with there data types and NULL/NOT NULL. We move to Alter the table. Table altering is an instruction for the query in the table to be changed.
-  The next would be to Add Contraint, in this case, add the ProductSubCategory key which is each category's unique identifer as the PrimaryKey constraint.
-  End and GO to mark the end of the batch, and instructing SQL to execute all preceding code as a single operation.

## dim.Territory Creation: 

 This is the territory of sales and it contains the country, region and continent of sales.

 # Code Explanation

 -  First query SQl using the IF NOT EXIST statement to ascertain the existence of table name Territory in the dim schema
-  If not exist, the begin syntax will start the process to create the dim. Territory table
-  The required columns are description of the Territory such as TerritoryKey, Region, Country and Continent. The TerritoryKey is the unique identifier for each of the Territory and would be used as the primary key,  Datatype int refers to the data type of numerical values. NOT NULL refers to values can not be empty. The nvarchar data type is used for Region,Country and ccontinent as they contain texts.
-  After specifying the columns with there data types and NULL/NOT NULL. We move to Alter the table. Table altering is an instruction for the query in the table to be changed.
-  The next would be to Add Contraint, in this case, add the ProductSubCategory key which is each category's unique identifer as the PrimaryKey constraint.
-  End and GO to mark the end of the batch, and instructing SQL to execute all preceding code as a single operation.


Following the above steps, below are the queries executed in sql to create the dim. tables

```sql
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dim' AND TABLE_NAME = 'Calendar')
BEGIN

CREATE TABLE dim.Calendar
(
    --pkdate_id INT IDENTITY(1000,1) NOT NULL,
	[OrderDate] [datetime2](0) NOT NULL,
	[Year] [int] NOT NULL,
	[Quarter] [int] NOT NULL,
	[Month] [int] NOT NULL,
	[MonthName] [varchar](10) NOT NULL
);
 
	ALTER TABLE dim.Calendar
	ADD CONSTRAINT PK_Calendar_Julian PRIMARY KEY([OrderDate]);
 
	--ALTER TABLE dim.Calendar
    --ADD CONSTRAINT UC_Calendar UNIQUE (Year);
END
 
GO

/*********************************************************/
/******************  Customer DIM DDL   ******************/
/*********************************************************/

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dim' AND TABLE_NAME = 'Customers')
BEGIN
	
    CREATE TABLE [dim].[Customers](
	[CustomerKey] [int] NOT NULL,
	[Full Name] [nvarchar](max) NOT NULL,
	[BirthDate] [nvarchar](max) NULL,
	[Gender] [nvarchar](max) NULL,
	[EmailAddress] [nvarchar](max) NULL,
	[TotalChildren] [nvarchar](25) NULL,
	[EducationLevel] [nvarchar](max) NULL,
	[Occupation] [nvarchar](max) NULL,
	[HomeOwner] [nvarchar](max) NULL,
	[Parent] [nvarchar](max) NULL,
	[Customer priority] [nvarchar](max) NULL,
	[Income Level] [nvarchar](max) NULL,
	[Education Level] [nvarchar](max) NULL,
	)
	;

	ALTER TABLE dim.Customers
    ADD CONSTRAINT PK_Cus_Key PRIMARY KEY (CustomerKey);

END;

GO

/*********************************************************/
/******************  Product Categories DIM DDL    ******************/
/*********************************************************/
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dim' AND TABLE_NAME = 'Product_Categories')
BEGIN

CREATE TABLE dim.Product_Categories
(
    ProductCategoryKey int NOT NULL,
	CategoryName nvarchar(max) NOT NULL,
	
);
ALTER TABLE dim.Product_Categories
ADD CONSTRAINT PK_Prodcat PRIMARY KEY(ProductCategoryKey);

END;
GO


/*********************************************************/
/******************  Product DIM DDL   ******************/
/*********************************************************/

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dim' AND TABLE_NAME = 'Product')
BEGIN
    CREATE TABLE dim.Product(
	--pkProdId bigint NOT NULL,
	ProductKey int NOT NULL,
	ProductSubcategoryKey int NOT NULL,
	ProductName nvarchar(max) NOT NULL,
	ProductColor nvarchar(max) NOT NULL,
	ProductCost money NULL,
	ProductPrice money NOT NULL,
	[Discount Price] decimal NOT NULL

);

ALTER TABLE dim.Product
ADD CONSTRAINT PK_Prod PRIMARY KEY(ProductKey);
	

END

GO
/*********************************************************/
/******************  Products DIM DDL   ******************/
/*********************************************************/

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dim' AND TABLE_NAME = 'Products')
BEGIN
    CREATE TABLE dim.Products(
	--pkProdId int NOT NULL,
	ProductKey int NOT NULL,
	ProductSubcategoryKey int NOT NULL,
	ProductName nvarchar(max) NOT NULL,
	ProductColor nvarchar(max) NOT NULL,
	ProductCost money NULL,
	ProductPrice money NOT NULL,
	[Discount Price] decimal NOT NULL

);

ALTER TABLE dim.Products
ADD CONSTRAINT PK_Prods PRIMARY KEY(ProductKey);
	

END

GO


/*********************************************************/
/******************  Territory DIM DDL    ******************/
/*********************************************************/
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dim' AND TABLE_NAME = 'Territory')
BEGIN


CREATE TABLE dim.Territory
(
    TerritoryKey int NOT NULL,
	Region nvarchar(max) NOT NULL,
	Country nvarchar(max) NOT NULL,
	Continent nvarchar(max) NOT NULL
);

ALTER TABLE dim.Territory
ADD CONSTRAINT PK_Territory PRIMARY KEY(TerritoryKey);

END

GO

/*********************************************************/
/******************  Product SubCategories DIM DDL    ******************/
/*********************************************************/
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dim' AND TABLE_NAME = 'Product_SubCategories')
BEGIN

CREATE TABLE dim.Product_SubCategories
(
    ProductSubcategoryKey int NOT NULL,
	SubcategoryName nvarchar(max) NOT NULL,
	ProductCategoryKey int NOT NULL,
	
);
ALTER TABLE dim.Product_SubCategories
ADD CONSTRAINT PK_Prodscat PRIMARY KEY(ProductSubcategoryKey);

END;


```

##  Fact Table

Two fact tables named Sales and Return tables are used for this project.

-  **Sales Fact Table:** This contains the measurable and quantifiable data useful for analysis and reporting on the key perfoemance metrics of Adventure works such as Quantity sold, revenue and profit. This table establishes foreign key relationships to related dimension tables.

-  **Return Fact Table:** This table contains the quantity of items returned after sales and useful for analysis on product defects and quality control analysis. This table establishes foreign key relationships to related dimension tables.

# Steps to Fact Table Creation

# Sales Fact Table

# Code Explanation
-  The query begins with quering the system with the IF EXISTS statement. This instructs the system to check if the table f.Sales exists in the schema f. The query then check the information schema tables for a table named Sales in schema f.
-  If the table exists, it drops it with the DROP TABLE f.Sales
-  It then proceeds to create a fact table named Sales in the schema f
-  The columns for the table are defined as Orderdate, OrderNumber,ProductKey,CustomerKey, TerritoryKey,ProductCatKey, OrderQuantity, RetailPrice and Revenue.
-  Each of the above are assigned data type based on their characteristics. Columns with values as numeric are assigned data type int, Orderdate is assigned as a datatime, OrderNumber is assigned data type nvarchar as it contains different language and ways of writing. Monetary column such as Retail price and Revenue were assigned decimal.
-  Values that cannot be empty were assigned as NOT NULL< values that can be empty were assigned as NULL.
-  The next step will be to alter the table by assigning foreign key.

**#Assigning OrderDate as ForeignKeys to the Sales table:**
-  Table name : f.Sales
-  Assign OrderDate as Foreign Key
-  The relationship will be the dim.Calendar Table which contains the (OrderDate) as primarykey
-  This links the OrderDate in f.Sales to the OrderDate in the dim.Calendar table. This allows the system to categorize sales by date-related attributes like day, month, quarter, year, etc.

**#Assigning CustomerKeys as ForeignKey to the Sales table:**
-  Table name : f.Sales
-  Assign CustomerKey as Foreign Key
-  The relationship will be the dim.Customers Table which contains the (CustomerKey) as primarykey
-  This links the CustomerKey in f.Sales to the CustomerKey in the dim.Customers table. This enables analysis by customer demographics, regions, etc.

**#Assigning ProductKey as ForeignKey to the Sales table:**
-  Table name : f.Sales
-  Assign ProductKey as Foreign Key
-  The relationship will be the dim.Products Table which contains the (ProductKey) as primarykey
-  This links the ProductKey in f.Sales to the ProductKey in the dim.Products table. This allows analysis by product type, category, and so on.


**#Assigning TerritotyKey as ForeignKey to the Sales table:**
-  Table name : f.Sales
-  Assign TerritoryKey as Foreign Key
-  The relationship will be the dim.Territory Table which contains the (TerritoryKey) as primarykey
-  This links the TerritoryKey in f.Sales to the TerritoryKey in the dim.Territory table. This supports geographical analysis (like sales by country, state, or region).

# Returns Fact Table

# Code Explanation
-  The query begins with quering the system with the IF EXISTS statement. This instructs the system to check if the table f.Returns exists in the schema f. The query then check the information schema tables for a table named Returns in schema f.
-  If the table exists, it drops it with the DROP TABLE f.returns
-  It then proceeds to create a fact table named Returns in the schema f
-  The columns for the table are defined as Returnate, ProductKey, TerritoryKey, ReturnQuantity
-  Each of the above are assigned data type based on their characteristics. Columns with values as numeric are assigned data type int, Returndate is assigned as a datatime, Productkey,TerritoryKey and ReturnQuantity are assigned and int data type because they are numerical.
-  Values that cannot be empty were assigned as NOT NULL< values that can be empty were assigned as NULL.
-  The next step will be to alter the table by assigning foreign key.

**#Assigning ReturnDate as ForeignKeys to the Returns table:**
-  Table name : f.Returns
-  Assign ReturnDate as Foreign Key
-  The relationship will be the dim.Calendar Table which contains the (OrderDate) as primarykey
-  This links the ReturnDate in f.Returnss to the OrderDate in the dim.Calendar table. This allows the system to categorize returns by date-related attributes like day, month, quarter, year, etc.

**#Assigning ProductKey as ForeignKey to the Returns table:**
-  Table name : f.Returns
-  Assign ProductKey as Foreign Key
-  The relationship will be the dim.Products Table which contains the (ProductKey) as primarykey
-  This links the ProductKey in f.Returns to the ProductKey in the dim.Products table. This allows return analysis by product type, category, and so on.

**#Assigning TerritotyKey as ForeignKey to the Returns table:**
-  Table name : f.Returns
-  Assign TerritoryKey as Foreign Key
-  The relationship will be the dim.Territory Table which contains the (TerritoryKey) as primarykey
-  This links the TerritoryKey in f.Returns to the TerritoryKey in the dim.Territory table. This supports geographical analysis (like sales by country, state, or region).

# When this is done, the below query will be generated and executed



```sql
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'f' AND TABLE_NAME = 'Sales')
BEGIN 

  DROP TABLE f.Sales;
END;


CREATE TABLE f.Sales(
	OrderDate datetime2(0) NOT NULL,
	--Order Year  int NOT NULL,
	OrderNumber nvarchar(50) NOT NULL,
	ProductKey int NOT NULL,
	CustomerKey int NOT NULL,
	TerritoryKey int NOT NULL,
	ProductCatKey int NULL,
	OrderQuantity int NOT NULL,
	RetailPrice decimal NOT NULL,
	Revenue decimal NOT NULL,

);

ALTER TABLE f.Sales--This is an instruction to change what is in the above query
ADD CONSTRAINT FK_SalestoCAL
	FOREIGN KEY (OrderDate)              -- FROM the LOCAL TABLE
	 REFERENCES  dim.Calendar(OrderDate) -- TO the FOREIGN TABLE
;

ALTER TABLE f.Sales --This is an instruction to change what is in the above query
ADD CONSTRAINT FK_SalestoCus 
    FOREIGN KEY (CustomerKey) 
	 REFERENCES dim.Customers(CustomerKey);

ALTER TABLE f.Sales--This is an instruction to change what is in the above query
ADD CONSTRAINT FK_SalestoProd
	FOREIGN KEY (ProductKey)      -- FROM the LOCAL TABLE
	 REFERENCES dim.Products(ProductKey)   -- TO the FOREIGN TABLE
;

ALTER TABLE f.Sales--This is an instruction to change what is in the above query
ADD CONSTRAINT FK_Territory
	FOREIGN KEY (TerritoryKey)    -- FROM the LOCAL TABLE
	 REFERENCES dim.Territory(TerritoryKey)  -- TO the FOREIGN TABLE
;


/*********************************************************/
/******************  Returns f.Table  ******************/
/*********************************************************/

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'f' AND TABLE_NAME = 'Returns')
BEGIN 

  DROP TABLE f.Returns;
END;

CREATE TABLE f.Returns(
	ReturnDate datetime2(0) NOT NULL,
	--Order Year  int NOT NULL,
	ProductKey int NOT NULL,
	TerritoryKey int NOT NULL,
	ReturnQuantity int NOT NULL,

);

ALTER TABLE f.Returns--This is an instruction to change what is in the above query
ADD CONSTRAINT FK_ReturnstoCAL
	FOREIGN KEY (ReturnDate)              -- FROM the LOCAL TABLE
	 REFERENCES  dim.Calendar(OrderDate) -- TO the FOREIGN TABLE
;

ALTER TABLE f.Returns--This is an instruction to change what is in the above query
ADD CONSTRAINT FK_ReturnstoProd
	FOREIGN KEY (ProductKey)      -- FROM the LOCAL TABLE
	 REFERENCES dim.Products(ProductKey)   -- TO the FOREIGN TABLE
;

ALTER TABLE f.Returns--This is an instruction to change what is in the above query
ADD CONSTRAINT FK_ReturnsTerritory
	FOREIGN KEY (TerritoryKey)    -- FROM the LOCAL TABLE
	 REFERENCES dim.Territory(TerritoryKey)  -- TO the FOREIGN TABLE

;


```

##  **Loading the Created dim and Fact Tables known as DML**

#**Steps**
<a name="lists" />

1. Exporting data to the created schema stg using DAX Studio. the stg alson called the staging table is a table to temporarily hold data.
2. Importing the data from the stg to the created dim and facts table.

/******************  **Load Dim.Calendar Table**  ******************/

# Code Explanation

-  The first syntax is to check if the dim.Calendar is empty by counting all rows in the dim.calendar.
-  If the row count is 0, the code inside the BEGIN....END block runs. This is to avoid duplicate entries if the table is already populated.
-  The next is to declare the variables by stratdate which is set at January 1 2020 and then the end date.
-  The next instruction is to loop through each day. Each time the loop runs, it inserts a new row for @Date in the dim.Calendar, and then moves to the next day.
-  The next would be to insert the date (OrderDate, Year, Quarter, Month, MonthName) and its attributes into the dim.Calendar
-  Values are assigned to each attributes such as OrderDate as @Date which is the current date in the loop, Year as Year(@Date) to extract the year from the @Date, DatePART(Quarter,@Date) to extarcts the 4 quartes of the year from @Date, Month as Month(@date to extarct the 1 to 12 months in the year, MonthName as DATENAME(Month,@Date) which extracts the full name of the month)
-  By doing the above, each day gets a new row in the order: OrderDate, year, Quarter, Month and MonthName.
-  The next will be to set the Date increment, which means that the date is moved forward by 1 day and this increases until the dates reaches the @EndDate.
-  The Go is a batch seperator for codes


/******************  **Load Dim.Customers Table**  ******************/

# Code Explanation

-  The purpose is to inserts new customer records from the stg. Customer_Lookup into the dim.Cusotmers table. 
-  The next step is to identify the columns to be included in the customers table such as ( Customerkey,FullName, Education Level, Income level and Occupation). This is important as it gives thew system order to arrnage the column.
-  FROM indicates the source table which in this case is the stg.Customer Lookup.
- The selected columns must tally with the specified listing in the Insert to statement. An dthis ensures that only the necessary columns are retirved from the stg.Customer Lookup table.
-  The Where clause is to ensure that only customers who do not already exist in the dim. Customers table are inserted.
-  Go is the batch seperator

/******************  **Load Dim.Product Table*  ******************/

# Code Explanation

-  The purpose is to inserts new products records from the stg. Product_Lookup into the dim.Products table. 
-  The next step is to identify the columns to be included in the customers table such as (Productkey,ProductName, ProductColor, Product Price and Discount price). This is important as it gives the system order to arrnage the column.
-  FROM indicates the source table which in this case is the stg.Product Lookup.
- The selected columns must tally with the specified listing in the Insert to statement. And this ensures that only the necessary columns are retirved from the stg.Products Lookup table. The try cast was used to ensure that only valid integers are inserted for the prodyuct key.
-  Data Validation uses the WHERE clause to filter the products, ensuring that only valid and unique products are inserted. And it contains 2 key conditions which are to filter out Non-Numeric products key if any exists adn to avoid duplicates.
-  Go is the batch seperator

/******************  **Load Dim.ProductCategory Table*  ******************/

# Code Explanation

-  The purpose is to insert new productcategory records from the stg. ProductCategory_Lookup into the dim.ProductsCategory table. 
-  The next step is to identify the columns to be included in the ProductCategoty table such as (Productcategorykey and ProductName). This is important as it gives the system order to arrange the column.
-  The SELECT statement retrives data from the stg.ProductCategoties Lookup staging table using an alis pcat
-  FROM indicates the source table which in this case is the stg.Product Lookup.
- The selected columns must tally with the specified listing in the Insert to statement. And this ensures that only the necessary columns are retirved from the stg.Products Lookup table.
-  Data Validation uses the the WHERE clause to avoid duplicates.
-  NOT IN (SELECT ProductCategoryKey FROM dim.Product_Categories) checks if pcat.ProductCategoryKey does not already exist in dim.Product_Categories.
-  Go is the batch seperator

/******************  **Load Dim.ProductSubCategory Table*  ******************/

# Code Explanation

-  The purpose is to inserts new products records from the stg. ProductSubcategory_Lookup into the dim.ProductsSubcatergories table and to avoid duplicate subcategories that are already in dim.Product_SubCategories.
-  The next step is to identify the columns to be included in the productsubcategory table such as (ProductSubcategorykey, SubCategoryName, ProductCategoryKey).This is important as it gives the system order to arrnage the column.
-  FROM indicates the source table which in this case is the stg.ProductSubcategory Lookup.
- The selected columns must tally with the specified listing in the Insert to statement. And this ensures that only the necessary columns are retirved from the stg.Products Lookup table.
-  Data Validation uses the the WHERE clause filters the products, ensuring that only valid and unique products are inserted. And it contains 2 key conditions whicha re to filter out Non-Numeric productsubcategory key if any exists adn to avoid duplicates.
-  Go is the batch seperator


/******************  **Load Dim.Territory Table*  ******************/

# Code Explanation

-  The purpose is to Insert new territory records into the dim.Territory dimension table and to avoid inserting duplicate territories by checking if the territorykey already exists in the dim.Territory table
-  The next step is to identify the columns to be included in the Territory table such as (Territorykey, Region, Country and Continent).This is important as it gives the system order to arrnage the column.
-  The SELECT statement gets the column bnames form the stging tabl using an alias t.
-  FROM indicates the source table which in this case is the stg.Territory Lookup.
- The selected columns must tally with the specified listing in the Insert to statement. And this ensures that only the necessary columns are retirved from the stg.Products Lookup table.
-  Data Validation uses the the WHERE clause filters the Territory, ensuring that only valid and unique products are inserted. And it contains 2 key conditions whicha re to filter out Non-Numeric products key if any exists and to avoid duplicates.
-  Go is the batch seperator

/******************  **Load facts Table*  ******************/

-  This query populates the f.Sales fact table from the staging table stg.[qSales Data].
-  The target table is the f.Sales and the columns are specified for insertion of values. Columns such as OrderDate, ordernNumber,ProductKey,CustomerKey,territoryKey,OrderQuantity, Retail Price and revenue.
-  These column names are selected using an alias s.
-  FROM statement indicates the source to come from the staging table.

/******************  **Load factReturns Table*  ******************/

-  This query populates the f.Returnss fact table from the staging table stg.[qReturns Data].
-  The target table is the f.Sales and the columns are specified for insertion of values. Columns such as ReturnDate, ProductKey,territoryKey,ReturnedQuantity).
-  These column names are selected using an alias r.
-  FROM statement indicates the source to come from staging table.

## These steps produced the below queries

```sql

/*********************************************************/
/******************  Load Dim.Calendar Table  ******************/
/*********************************************************/
 
IF (SELECT COUNT(*) FROM dim.Calendar) = 0
BEGIN
    -- Declare variables
    DECLARE @StartDate DATE = '2020-01-01';
    DECLARE @EndDate DATE = DATEADD(year, 3, GETDATE());
    DECLARE @Date DATE = @StartDate;
 
    -- Populate the Calendar table
    WHILE @Date <= @EndDate
    BEGIN
        INSERT INTO dim.Calendar (
            [OrderDate], 
            [Year], 
            [Quarter], 
            [Month], 
            [MonthName]
        )
        VALUES (
            @Date,
            YEAR(@Date),
            DATEPART(QUARTER, @Date),
            MONTH(@Date),
            DATENAME(MONTH, @Date)
        );
 
        -- Increment the date
        SET @Date = DATEADD(DAY, 1, @Date);
    END;
END;
GO

/*********************************************************/
/******************  Load Dim.Customer Table  ******************/
/*********************************************************/
GO

INSERT INTO dim.Customers(CustomerKey, [Full Name], EducationLevel, [Income Level], Occupation)
	SELECT cus.CustomerKey
		  ,cus.[Full Name]
		  ,cus.EducationLevel
		  ,cus.[Income Level]
		  ,cus.Occupation
	FROM stg.[Customer Lookup] cus
	WHERE cus.CustomerKey NOT IN (SELECT CustomerKey FROM dim.Customers)

;
GO

/*********************************************************/
/******************  Load Dim.Product_Categories Table  ******************/
/*********************************************************/
GO

INSERT INTO dim.Product_Categories(ProductCategoryKey, CategoryName)
SELECT pcat.ProductCategoryKey
      ,pcat.CategoryName
FROM stg.[Product Categories Lookup] pcat
WHERE pcat.ProductCategoryKey not in (SELECT ProductcategoryKey FROM dim.Product_categories)
;
GO


/*********************************************************/
/******************  Load Dim.Product Table  ******************/
/*********************************************************/


INSERT INTO dim.Products (ProductKey, ProductSubcategoryKey, ProductName, ProductColor, ProductCost, ProductPrice, [Discount Price])
SELECT 
       TRY_CAST(prod.ProductKey AS INT) AS ProductKey,
       prod.ProductSubcategoryKey,
       prod.ProductName,
       prod.ProductColor,
       prod.ProductCost,
       prod.ProductPrice,
       prod.[Discount Price]
FROM stg.[Product Lookup] prod
WHERE 
    TRY_CAST(prod.ProductKey AS INT) IS NOT NULL -- Ensure only valid numeric values are considered
    AND TRY_CAST(prod.ProductKey AS INT) NOT IN (SELECT ProductKey FROM dim.Products);


GO

/*********************************************************/
/******************  Load Dim.Territory Table  ******************/
/*********************************************************/
GO

INSERT INTO dim.Territory(TerritoryKey,Region,Country,Continent)
SELECT t.SalesTerritoryKey
      ,t.Region
	  ,t.Country
	  ,t.Continent
FROM stg.[Territory Lookup] t
WHERE t.SalesTerritoryKey not in (SELECT TerritoryKey FROM dim.Territory)
;
GO

/*********************************************************/
/******************  Load Dim.Product_Categories Table  ******************/
/*********************************************************/
GO

INSERT INTO dim.Product_SubCategories(ProductSubcategoryKey, SubcategoryName, ProductCategoryKey)
SELECT pscat.ProductSubcategoryKey
      ,pscat.SubcategoryName
	  ,pscat.ProductCategoryKey
FROM stg.[Product Subcategories Lookup] pscat
WHERE pscat.ProductSubcategoryKey not in (SELECT ProductSubcategoryKey FROM dim.Product_SubCategories)
;
GO

/*********************************************************/
/******************  Fact TableLoaders  ******************/
/*********************************************************/


/******************  Orders f.Sales Fact   ******************/


INSERT INTO f.Sales(OrderDate, OrderNumber, ProductKey, CustomerKey, TerritoryKey, OrderQuantity, RetailPrice, Revenue)
SELECT s.OrderDate
	  ,s.OrderNumber
	  ,s.ProductKey
	  ,s.Customerkey
	  ,s.TerritoryKey
	  ,s.OrderQuantity
	  ,s.[Retail Price]
	  ,s.Revenue
FROM stg.[qSales Data] s


;


/******************   f.Returns   ******************/


INSERT INTO Project.f.Returns(ReturnDate, ProductKey, TerritoryKey, ReturnQuantity)
SELECT r.ReturnDate
	  ,r.ProductKey
	  ,r.TerritoryKey
	  ,r.ReturnQuantity
FROM stg.[qReturns Data] r


;


```

In [1]:
USE Project;
GO

/*********************************************************/
/******************    Schema DDL       ******************/
/*********************************************************/

IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'dim' ) 
BEGIN
	EXEC sp_executesql N'CREATE SCHEMA dim AUTHORIZATION dbo;'
END
;

GO

IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'stg' ) 
BEGIN
	EXEC sp_executesql N'CREATE SCHEMA stg AUTHORIZATION dbo;'
END
;

GO

IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'f' ) 
BEGIN
	EXEC sp_executesql N'CREATE SCHEMA f AUTHORIZATION dbo;'
END
;

GO

--- Brought in the tables using dax studio to the created stg schema0


/*********************************************************/
/******************   DIM DDL   ******************/
/*********************************************************/


/*********************************************************/
/******************  Calendar Dim DDL   ******************/
/*********************************************************/

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dim' AND TABLE_NAME = 'Calendar')
BEGIN

CREATE TABLE dim.Calendar
(
    --pkdate_id INT IDENTITY(1000,1) NOT NULL,
	[OrderDate] [datetime2](0) NOT NULL,
	[Year] [int] NOT NULL,
	[Quarter] [int] NOT NULL,
	[Month] [int] NOT NULL,
	[MonthName] [varchar](10) NOT NULL
);
 
	ALTER TABLE dim.Calendar
	ADD CONSTRAINT PK_Calendar_Julian PRIMARY KEY([OrderDate]);
 
	--ALTER TABLE dim.Calendar
    --ADD CONSTRAINT UC_Calendar UNIQUE (Year);
END
 
GO

/*********************************************************/
/******************  Customer DIM DDL   ******************/
/*********************************************************/

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dim' AND TABLE_NAME = 'Customers')
BEGIN
	
    CREATE TABLE [dim].[Customers](
	[CustomerKey] [int] NOT NULL,
	[Full Name] [nvarchar](max) NOT NULL,
	[BirthDate] [nvarchar](max) NULL,
	[Gender] [nvarchar](max) NULL,
	[EmailAddress] [nvarchar](max) NULL,
	[TotalChildren] [nvarchar](25) NULL,
	[EducationLevel] [nvarchar](max) NULL,
	[Occupation] [nvarchar](max) NULL,
	[HomeOwner] [nvarchar](max) NULL,
	[Parent] [nvarchar](max) NULL,
	[Customer priority] [nvarchar](max) NULL,
	[Income Level] [nvarchar](max) NULL,
	[Education Level] [nvarchar](max) NULL,
	)
	;

	ALTER TABLE dim.Customers
    ADD CONSTRAINT PK_Cus_Key PRIMARY KEY (CustomerKey);

END;

GO

/*********************************************************/
/******************  Product Categories DIM DDL    ******************/
/*********************************************************/
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dim' AND TABLE_NAME = 'Product_Categories')
BEGIN

CREATE TABLE dim.Product_Categories
(
    ProductCategoryKey int NOT NULL,
	CategoryName nvarchar(max) NOT NULL,
	
);
ALTER TABLE dim.Product_Categories
ADD CONSTRAINT PK_Prodcat PRIMARY KEY(ProductCategoryKey);

END;
GO


/*********************************************************/
/******************  Product DIM DDL   ******************/
/*********************************************************/

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dim' AND TABLE_NAME = 'Product')
BEGIN
    CREATE TABLE dim.Product(
	--pkProdId bigint NOT NULL,
	ProductKey int NOT NULL,
	ProductSubcategoryKey int NOT NULL,
	ProductName nvarchar(max) NOT NULL,
	ProductColor nvarchar(max) NOT NULL,
	ProductCost money NULL,
	ProductPrice money NOT NULL,
	[Discount Price] decimal NOT NULL

);

ALTER TABLE dim.Product
ADD CONSTRAINT PK_Prod PRIMARY KEY(ProductKey);
	

END

GO
/*********************************************************/
/******************  Products DIM DDL   ******************/
/*********************************************************/

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dim' AND TABLE_NAME = 'Products')
BEGIN
    CREATE TABLE dim.Products(
	--pkProdId int NOT NULL,
	ProductKey int NOT NULL,
	ProductSubcategoryKey int NOT NULL,
	ProductName nvarchar(max) NOT NULL,
	ProductColor nvarchar(max) NOT NULL,
	ProductCost money NULL,
	ProductPrice money NOT NULL,
	[Discount Price] decimal NOT NULL

);

ALTER TABLE dim.Products
ADD CONSTRAINT PK_Prods PRIMARY KEY(ProductKey);
	

END

GO



/*********************************************************/
/******************  Territory DIM DDL    ******************/
/*********************************************************/
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dim' AND TABLE_NAME = 'Territory')
BEGIN


CREATE TABLE dim.Territory
(
    TerritoryKey int NOT NULL,
	Region nvarchar(max) NOT NULL,
	Country nvarchar(max) NOT NULL,
	Continent nvarchar(max) NOT NULL
);

ALTER TABLE dim.Territory
ADD CONSTRAINT PK_Territory PRIMARY KEY(TerritoryKey);

END

GO

/*********************************************************/
/******************  Product SubCategories DIM DDL    ******************/
/*********************************************************/
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dim' AND TABLE_NAME = 'Product_SubCategories')
BEGIN

CREATE TABLE dim.Product_SubCategories
(
    ProductSubcategoryKey int NOT NULL,
	SubcategoryName nvarchar(max) NOT NULL,
	ProductCategoryKey int NOT NULL,
	
);
ALTER TABLE dim.Product_SubCategories
ADD CONSTRAINT PK_Prodscat PRIMARY KEY(ProductSubcategoryKey);

END;




/*********************************************************/
/*********************************************************/
/*********************************************************/
/******************  Fact Table Builds  ******************/
/*********************************************************/
/*********************************************************/
/*********************************************************/


/*********************************************************/
/******************  Sales f.Table  ******************/
/*********************************************************/


IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'f' AND TABLE_NAME = 'Sales')
BEGIN 

  DROP TABLE f.Sales;
END;


CREATE TABLE f.Sales(
	OrderDate datetime2(0) NOT NULL,
	--Order Year  int NOT NULL,
	OrderNumber nvarchar(50) NOT NULL,
	ProductKey int NOT NULL,
	CustomerKey int NOT NULL,
	TerritoryKey int NOT NULL,
	ProductCatKey int NULL,
	OrderQuantity int NOT NULL,
	RetailPrice decimal NOT NULL,
	Revenue decimal NOT NULL,

);



ALTER TABLE f.Sales
ADD CONSTRAINT FK_SalestoCAL
	FOREIGN KEY (OrderDate)              -- FROM the LOCAL TABLE
	 REFERENCES  dim.Calendar(OrderDate) -- TO the FOREIGN TABLE
;


ALTER TABLE f.Sales 
ADD CONSTRAINT FK_SalestoCus 
    FOREIGN KEY (CustomerKey) 
	 REFERENCES dim.Customers(CustomerKey);

ALTER TABLE f.Sales
ADD CONSTRAINT FK_SalestoProd
	FOREIGN KEY (ProductKey)      -- FROM the LOCAL TABLE
	 REFERENCES dim.Products(ProductKey)   -- TO the FOREIGN TABLE
;


ALTER TABLE f.Sales
ADD CONSTRAINT FK_Territory
	FOREIGN KEY (TerritoryKey)    -- FROM the LOCAL TABLE
	 REFERENCES dim.Territory(TerritoryKey)  -- TO the FOREIGN TABLE
;


/*********************************************************/
/******************  Returns f.Table  ******************/
/*********************************************************/

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'f' AND TABLE_NAME = 'Returns')
BEGIN 

  DROP TABLE f.Returns;
END;

CREATE TABLE f.Returns(
	ReturnDate datetime2(0) NOT NULL,
	--Order Year  int NOT NULL,
	ProductKey int NOT NULL,
	TerritoryKey int NOT NULL,
	ReturnQuantity int NOT NULL,


);


ALTER TABLE f.Returns
ADD CONSTRAINT FK_ReturnstoCAL
	FOREIGN KEY (ReturnDate)              -- FROM the LOCAL TABLE
	 REFERENCES  dim.Calendar(OrderDate) -- TO the FOREIGN TABLE
;


ALTER TABLE f.Returns
ADD CONSTRAINT FK_ReturnstoProd
	FOREIGN KEY (ProductKey)      -- FROM the LOCAL TABLE
	 REFERENCES dim.Products(ProductKey)   -- TO the FOREIGN TABLE
;


ALTER TABLE f.Returns
ADD CONSTRAINT FK_ReturnsTerritory
	FOREIGN KEY (TerritoryKey)    -- FROM the LOCAL TABLE
	 REFERENCES dim.Territory(TerritoryKey)  -- TO the FOREIGN TABLE

;



/*********************************************************/
/******************    Loading DML       ******************/
/*********************************************************/

/*********************************************************/
/******************  Load Dim.Calendar Table  ******************/
/*********************************************************/
 
IF (SELECT COUNT(*) FROM dim.Calendar) = 0
BEGIN
    -- Declare variables
    DECLARE @StartDate DATE = '2020-01-01';
    DECLARE @EndDate DATE = DATEADD(year, 3, GETDATE());
    DECLARE @Date DATE = @StartDate;
 
    -- Populate the Calendar table
    WHILE @Date <= @EndDate
    BEGIN
        INSERT INTO dim.Calendar (
            [OrderDate], 
            [Year], 
            [Quarter], 
            [Month], 
            [MonthName]
        )
        VALUES (
            @Date,
            YEAR(@Date),
            DATEPART(QUARTER, @Date),
            MONTH(@Date),
            DATENAME(MONTH, @Date)
        );
 
        -- Increment the date
        SET @Date = DATEADD(DAY, 1, @Date);
    END;
END;
GO

/*********************************************************/
/******************  Load Dim.Customer Table  ******************/
/*********************************************************/
GO

INSERT INTO dim.Customers(CustomerKey, [Full Name], EducationLevel, [Income Level], Occupation)
	SELECT cus.CustomerKey
		  ,cus.[Full Name]
		  ,cus.EducationLevel
		  ,cus.[Income Level]
		  ,cus.Occupation
	FROM stg.[Customer Lookup] cus
	WHERE cus.CustomerKey NOT IN (SELECT CustomerKey FROM dim.Customers)

;
GO

/*********************************************************/
/******************  Load Dim.Product_Categories Table  ******************/
/*********************************************************/
GO

INSERT INTO dim.Product_Categories(ProductCategoryKey, CategoryName)
SELECT pcat.ProductCategoryKey
      ,pcat.CategoryName
FROM stg.[Product Categories Lookup] pcat
WHERE pcat.ProductCategoryKey not in (SELECT ProductcategoryKey FROM dim.Product_categories)
;
GO


/*********************************************************/
/******************  Load Dim.Product Table  ******************/
/*********************************************************/


INSERT INTO dim.Products (ProductKey, ProductSubcategoryKey, ProductName, ProductColor, ProductCost, ProductPrice, [Discount Price])
SELECT 
       TRY_CAST(prod.ProductKey AS INT) AS ProductKey,
       prod.ProductSubcategoryKey,
       prod.ProductName,
       prod.ProductColor,
       prod.ProductCost,
       prod.ProductPrice,
       prod.[Discount Price]
FROM stg.[Product Lookup] prod
WHERE 
    TRY_CAST(prod.ProductKey AS INT) IS NOT NULL -- Ensure only valid numeric values are considered
    AND TRY_CAST(prod.ProductKey AS INT) NOT IN (SELECT ProductKey FROM dim.Products);


GO

/*********************************************************/
/******************  Load Dim.Territory Table  ******************/
/*********************************************************/
GO

INSERT INTO dim.Territory(TerritoryKey,Region,Country,Continent)
SELECT t.SalesTerritoryKey
      ,t.Region
	  ,t.Country
	  ,t.Continent
FROM stg.[Territory Lookup] t
WHERE t.SalesTerritoryKey not in (SELECT TerritoryKey FROM dim.Territory)
;
GO

/*********************************************************/
/******************  Load Dim.Product_Categories Table  ******************/
/*********************************************************/
GO

INSERT INTO dim.Product_SubCategories(ProductSubcategoryKey, SubcategoryName, ProductCategoryKey)
SELECT pscat.ProductSubcategoryKey
      ,pscat.SubcategoryName
	  ,pscat.ProductCategoryKey
FROM stg.[Product Subcategories Lookup] pscat
WHERE pscat.ProductSubcategoryKey not in (SELECT ProductSubcategoryKey FROM dim.Product_SubCategories)
;
GO




/*********************************************************/
/******************  Fact TableLoaders  ******************/
/*********************************************************/


/******************  Orders f.Sales Fact   ******************/


INSERT INTO f.Sales(OrderDate, OrderNumber, ProductKey, CustomerKey, TerritoryKey, OrderQuantity, RetailPrice, Revenue)
SELECT s.OrderDate
	  ,s.OrderNumber
	  ,s.ProductKey
	  ,s.Customerkey
	  ,s.TerritoryKey
	  ,s.OrderQuantity
	  ,s.[Retail Price]
	  ,s.Revenue
FROM stg.[qSales Data] s


;



/******************   f.Returns   ******************/


INSERT INTO Project.f.Returns(ReturnDate, ProductKey, TerritoryKey, ReturnQuantity)
SELECT r.ReturnDate
	  ,r.ProductKey
	  ,r.TerritoryKey
	  ,r.ReturnQuantity
FROM stg.[qReturns Data] r


;